/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './charts.module';
import * as i2 from '@angular/common';
export const ChartsModuleNgFactory:i0.NgModuleFactory<i1.ChartsModule> = i0.ɵcmf(i1.ChartsModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.ChartsModule,i1.ChartsModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvREVWRUxPUEVSL0RvY3VtZW50cy9HaXRIdWIvdmVydmFsanMvdmVydmFsL3BhY2thZ2VzL2NoYXJ0cy9zcmMvY2hhcnRzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9ERVZFTE9QRVIvRG9jdW1lbnRzL0dpdEh1Yi92ZXJ2YWxqcy92ZXJ2YWwvcGFja2FnZXMvY2hhcnRzL3NyYy9jaGFydHMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
